### ISSUE TITLE
Add OSGi metadata

### ISSUE THREAD

**Issue by dpishchukhin** [patrickvankann/rxmqtt#13]

**Comment by patrickvankann** [comment]
Fair point. I'm a bit busy this week but I will try to add in the maven bundle plugin and then do a release ASAP.

**Comment by patrickvankann** [comment]
I propose adding the metadata without changing the packaging type from JAR using a combination of the maven-bundle-plugin and the jar plugin. When I do that, it generates a MANIFEST.MF with the following:

Manifest-Version: 1.0
Bnd-LastModified: 1510595951655
Build-Jdk: 1.8.0_144
Built-By: patvanka
Bundle-Description: An RxJava API for handling MQTT messages with an imp
 lementation using the Paho Java MQTT library.
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion: 2
Bundle-Name: rxmqtt
Bundle-SymbolicName: net.eusashead.mqtt.rxmqtt
Bundle-Version: 1.2.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Export-Package: net.eusashead.iot.mqtt;uses:="io.reactivex";version="1.2
 .0",net.eusashead.iot.mqtt.paho;uses:="io.reactivex,net.eusashead.iot.m
 qtt,org.eclipse.paho.client.mqttv3";version="1.2.0"
Import-Package: io.reactivex;version="[2.1,3)",io.reactivex.functions;ve
 rsion="[2.1,3)",net.eusashead.iot.mqtt,org.eclipse.paho.client.mqttv3;v
 ersion="[1.1,2)",org.eclipse.paho.client.mqttv3.persist;version="[1.1,2
 )"
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-3.3.0.201609221906

Is that sufficient for your needs?

**Comment by dpishchukhin** [comment]
Yes, fine. Thanks

**Comment by patrickvankann** [comment]
I've pushed a new release to Maven today (1.1.1.RELEASE) that features the OSGi metadata and upgrades to the Paho and RxJava2 dependencies. Can you let me know if that works for you and I will close this if so.
