### ISSUE TITLE
Question: why does a developer have to set MqttMessage.id explicitly? 

### ISSUE THREAD

**Issue by dpishchukhin** [patrickvankann/rxmqtt#14]
Paho generates an ID for every Message. Why is a developer responsible for this in your API?

**Comment by patrickvankann** [comment]
Hi,

Sorry it has taken me a while to look at this! You are quite correct as having read the Paho docs a bit more carefully I can see that there is no point in setting message ID at publish time as this will be ignored. 

I am thinking about splitting publish and subscribe messages into separate classes and not having message ID at all on publish messages. Any thoughts?

**Comment by patrickvankann** [comment]
I've committed some changes that effectively split messages that you publish from messages that you receive. For publish messages, you no longer need to provide an id - in fact you can't - there's no point, as Paho will ignore it anyhow. If you have any thoughts let me know. Plan to push out a release 1.2.0 with this change as soon as I can.

**Comment by patrickvankann** [comment]
FYI Version 1.2.0.RELEASE has just been released which addresses this.
