### ISSUE TITLE
Filter messages by topic

### ISSUE THREAD

**Issue by Andresteve07** [patrickvankann/rxmqtt#15]
Let it be a client subscribed to the topic: "ROOT/ALL-DEVICES/+" that waits for all the devices to send messages.
Then, one of those devices publishes a message to the topic: "ROOT/ALL-DEVICES/THIS-DEVICE"
Since the subscription receives messages from ALL devices I find necessary to employ a filter in order to detect which device that message comes from. 
Certainly adding more information ("source_device") to the message payload would work but that implies deserialization for each message.
So, reading the "publish topic" would be the go to solution for us, but it is only accesable on the `messageArrived(String topic, MqttMessage message)` paho method.

Would you consider adding the "publish topic" as an attribute of the class MqttMessage?
That would make the following snippet work:

```java
.
.
.

PublishProcessor<MqttMessage> receivedMessagesProcessor = PublishProcessor.create();
mMqttClient.subscribe("ROOT/ALL-DEVICES/+",2)
            .subscribeOn(Schedulers.io())
            .subscribe(mqttMessage -> receivedMessagesProcessor.onNext(mqttMessage));

this.getMessagesFromDevice("THIS-DEVICE");
.
.
.

public Flowable<MqttMessage> getMessagesFromDevice(String deviceSubtopic){
	return receivedMessagesProcessor
		.filter(mqttMessage -> mqttMessage.getTopic().equals(deviceSubtopic)) //Here!!!!!!
		.timeout(2000L, TimeUnit.MILLISECONDS)
		.firstElement();
}

```

**Comment by patrickvankann** [comment]
I hadn't considered the case where a wildcard topic was used and can see the need for the topic to be returned in the message. I think your approach is sound. I plan to address this and some other issues in a new release.

**Comment by patrickvankann** [comment]
I've committed a change that exposes topic on the SubscribeMessage. This is along with some other changes that split "publish" messages from "subscribe" messages (when publishing, you don't need either a topic or an id - there is no point in requiring API users to supply these fields). Let me know what you think. I will probably release 1.2.0 in the next few days.

**Comment by Andresteve07** [comment]
Hello Patrick, I've taken a look at the commit. All the changes introduced to the API do make a lot of sense to me.
I'm looking forward to the release. Thank you for considering this issue.

**Comment by patrickvankann** [comment]
Just pushed 1.2.0.RELEASE. Should be in Maven central soon. Let me know how it goes.
