### ISSUE TITLE
How to handle connection lost?

### ISSUE THREAD

**Issue by lostsakya** [patrickvankann/rxmqtt#20]

**Comment by lostsakya** [comment]
I use rxmqtt on android device.
I do something as follows, but I'm not sure problem is solved when connection lost.

1. `mqttConnectOptions.setAutomaticReconnect(true);
mqttConnectOptions.setCleanSession(false);`

2. `rxMqttClient
       .connect()
       .retry() //reconnect when exception happened 
       .andThen(rxMqttClient.subscribe(topics, qoses))
       .subscribe();
`

**Comment by patrickvankann** [comment]
Hi there,

I hadn't considered this scenario properly so it probably needs investigation. Are you getting any errors when the retry() is not succeeding? Have you had any thoughts about the best approach to resolve it?
